name: Data update
on:
  schedule:
    # ‚ÄúAt 00:00 every day‚Äù
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  pull-airtable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup env
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - name: "Pull data from Airtable"
        env:
          AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN}}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID}}
        run: touch .env && npm run airtable && rm .env
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: ü§ñ Damien's Robot
          author_email: damien+bot@erambert.me
          message: Update themes data
